### ISSUE TITLE
Parsing bug for msgstr with brackets [ ]

### ISSUE THREAD

**Issue by hangy** [maddingue/Locale-Maketext-Lexicon-Getcontext#3]
```
#   Failed test 'months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']'
#   at t/10-parse.t line 59.
#          got: '~['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'~]'
#     expected: '['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']'
# Looks like you failed 4 tests of 25.

```
From openfoodfacts/openfoodfacts-server#771

**Comment by maddingue** [comment]
This is actually caused by the transformation of the gettext syntax to the maketext syntax, as documented in [Locale::Maketext](https://metacpan.org/pod/Locale::Maketext#BRACKET-NOTATION). Given this won't be used in the context of ProductOpener, I've added an option `disable_maketext_conversion` which will do exactly what it means: avoid translating to maketext syntax. This will have the added bonus to make your use case a tiny bit faster.

[Release 0.05](https://metacpan.org/release/SAPER/Locale-Maketext-Lexicon-Getcontext-0.05) is on its way to the CPAN.
